'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Emme_Subic_Transport_Corporation_Payroll

    Partial Public Class TripSheet
        Public Property id As Integer
        Public Property user_id As Nullable(Of Integer)
        Public Property tripDate As Nullable(Of Date)
        Public Property fromLocation As String
        Public Property toLocation As String
        Public Property driverHelper As String
        Public Property broker As String
        Public Property containerNumber As String
        Public Property activityType As String
        Public Property Remarks As String
        Public Property WaybillNumber As String
        Public Property rate As Nullable(Of Double)
    
    End Class

End Namespace
