'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Emme_Subic_Transport_Corporation_Payroll

    Partial Public Class UserDetail
        Public Property Id As Integer
        Public Property fname As String
        Public Property mname As String
        Public Property lname As String
        Public Property birthdate As Nullable(Of Date)
        Public Property birthplace As String
        Public Property Cstatus As String
        Public Property Age As Nullable(Of Integer)
        Public Property CellphoneNo As String
        Public Property datehired As Nullable(Of Date)
        Public Property EmployeeStats As String
        Public Property Gender As String
        Public Property Religion As String
        Public Property Height As String
        Public Property Weight As String
        Public Property EmailAdd As String
        Public Property Caddress As String
        Public Property Paddress As String
        Public Property role As String
        Public Property Picture As Byte()
        Public Property created_at As Nullable(Of Date)
        Public Property isDeleted As Nullable(Of Byte)
        Public Property EmployeeID As String
        Public Property sss As String
        Public Property pagibig As String
        Public Property philhealth As String
        Public Property tin As String
        Public Property driverlicenseNumber As String
        Public Property driverlicenseRestrictionCode As String
        Public Property driverlicenseExpdate As Nullable(Of Date)
        Public Property ctapExpdate As Nullable(Of Date)
        Public Property medtestExpdate As Nullable(Of Date)
        Public Property medtestRemarks As String
        Public Property drugtestExpdate As Nullable(Of Date)
        Public Property drugtestMethamphetamine As String
        Public Property Tetrahydrocannabinol As String
        Public Property nbiclearanceExpdate As Nullable(Of Date)
        Public Property policeclearanceExpdate As Nullable(Of Date)
        Public Property brgyclearanceExpdate As Nullable(Of Date)
        Public Property atmNumber As String
        Public Property educationalBackground As String
        Public Property employementStatus As String
        Public Property dateofConversion As String
        Public Property numberofYears As String
        Public Property performanceObsStart As Nullable(Of Date)
        Public Property performanceObsEnd As Nullable(Of Date)
        Public Property probationaryStart As Nullable(Of Date)
        Public Property probationaryEnd As Nullable(Of Date)
    
    End Class

End Namespace
